spring:
  application:
    name: zuul-server
server:
  port: 5000
eureka:
  instance:
  appname: zuul-server
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    userapi:
      path: /userapi/**
      serviceId: user-server
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
zuul.prefix: /v1