server:
  port: 8888
  servlet:
    context-path: /

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        native:
          search-locations: classpath:/
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8