server:
  port: 8181
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/waitforyouwtt/back-stage/tree/master/config-server/src/main/resources
          username: waitforyouwtt
          password: wtt19940512577