server:
  port: 8181
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuanzicheng/spring-cloud-config-repository.git
          username: waitforyouwtt
          password: wtt19940512577