server:
  port: 8762
spring:
  application:
    name: user-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/waitforyouwtt/back-stage/tree/master/config-server
          username: waitforyouwtt
          password: wtt19940512577
